import "./globals.css";

import Header from "./components/Header";
import type { Metadata } from "next";
import { ReactNode } from "react";
import localFont from "next/font/local";

const pretendard = localFont({
  src: "./fonts/PretendardVariable.woff2",
  display: "swap",
  weight: "45 920",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: ReactNode;
  modal: ReactNode;
}>) {
  return (
    <html lang="ko" className={pretendard.className}>
      <body className="mx-auto max-w-4xl px-5">
        <Header />
        <main>{children}</main>
        {modal}
        <div id="modal-root"></div>
      </body>
    </html>
  );
}
